<a href="https://colab.research.google.com/github/Arijeet-Mahanty/House_Price_Predictor_Model/blob/main/House_Price_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Importing necessary Python Libraries

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

### Loading the dataset

In [ ]:
df = pd.read_csv("/content/sample_data/indian_house_prices.csv")
df.head()

,city,locality,bedrooms,bathrooms,sqft_living,sqft_lot,floors,year_built,year_renovated,property_type,parking,facing,lift,furnishing,nearby_schools,nearby_hospitals,society,balcony,garden,price
0,Mumbai,Andheri,3,2,2128,3321,3,1963,1973,Independent House,0,North,Yes,Furnished,3,4,Andheri Heights,1,No,25921000
1,Delhi,Vasant Kunj,5,3,353,3018,3,2004,2013,Villa,1,South,No,Furnished,1,3,Vasant Kunj Heights,2,No,4035000
2,Pune,Viman Nagar,1,4,4692,5764,2,1960,1996,Villa,1,North,Yes,Unfurnished,3,2,Viman Nagar Heights,1,Yes,40182000
3,Chennai,Adyar,4,3,1632,7747,2,1976,2017,Villa,0,South,Yes,Furnished,7,3,Adyar Enclave,1,No,13501000
4,Mumbai,Bandra,1,3,3586,5829,1,1977,2012,Villa,1,West,No,Unfurnished,7,1,Bandra Enclave,1,Yes,43257000

### Encoding non-numeric data to numeric format

In [ ]:
le = LabelEncoder()
df["CityIndex"] = le.fit_transform(df["city"])
df["LocalityIndex"] = le.fit_transform(df["locality"])
df["property_typeIndex"] = le.fit_transform(df["property_type"])
df.head()

,city,locality,bedrooms,bathrooms,sqft_living,sqft_lot,floors,year_built,year_renovated,property_type,...,furnishing,nearby_schools,nearby_hospitals,society,balcony,garden,price,CityIndex,LocalityIndex,property_typeIndex
0,Mumbai,Andheri,3,2,2128,3321,3,1963,1973,Independent House,...,Furnished,3,4,Andheri Heights,1,No,25921000,3,1,2
1,Delhi,Vasant Kunj,5,3,353,3018,3,2004,2013,Villa,...,Furnished,1,3,Vasant Kunj Heights,2,No,4035000,2,21,3
2,Pune,Viman Nagar,1,4,4692,5764,2,1960,1996,Villa,...,Unfurnished,3,2,Viman Nagar Heights,1,Yes,40182000,4,23,3
3,Chennai,Adyar,4,3,1632,7747,2,1976,2017,Villa,...,Furnished,7,3,Adyar Enclave,1,No,13501000,1,0,3
4,Mumbai,Bandra,1,3,3586,5829,1,1977,2012,Villa,...,Unfurnished,7,1,Bandra Enclave,1,Yes,43257000,3,4,3

### Defining Features and Target

In [ ]:
X = df[['CityIndex','LocalityIndex','sqft_living','floors','balcony','property_typeIndex']]
Y = df['price']

### Splitting The Dataset

In [ ]:
X_train, X_test ,Y_train, Y_test = train_test_split(X,Y,test_size=0.2,random_state=42)

### Train the linear model

In [ ]:
model = LinearRegression()
model.fit(X_train,Y_train)

Y_pred = model.predict(X_test)

print("R2 Score: ",r2_score(Y_test,Y_pred))

R2 Score:  0.9031331257744738

### Comparing the predicted data

In [ ]:
compare = pd.DataFrame({'Actual':Y_test,'Prediction':Y_pred.astype(int)})
compare.head()

       Actual  Prediction
521  28458000    23220126
737  39168500    44452131
740  32105000    29601288
660  23219000    27101151
411  19411000    21765251